name = "fikreislam"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".open-next"

[vars]
# NEXT_PUBLIC_ variables are baked into the build, but others need to be defined here or in the dashboard
# NEXT_PUBLIC_SUPABASE_URL = "..."
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "..."
# NEXT_PUBLIC_IA_ACCESS_KEY = "..."
# NEXT_PUBLIC_IA_SECRET_KEY = "..."
